spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-ctsoqq5umphs73fols10-a.ohio-postgres.render.com/cars_xokh
spring.datasource.username=tilin
spring.datasource.password=GaaM9zgvIMkt8Ml1Rw9SjWzmUkKASBqv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
firebase.api.key=AIzaSyDwctdFL5g4ftJFWGPiHPYdMZCabmfibRk
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
stripe.api.key=sk_test_51QWrbLP3YsBP4OQBvZsUtVLkxwalvOfo7nn994IxRmTwYwGYQlZsWdQ4I8wYPzCD9rPN8sI2FuAKUh0ol5KCKQdg00qMWjZFYB
management.endpoints.web.exposure.include=mappings










